language: node_js
os:
  - linux
node_js:
  - '12'
  # - '10'
script:
  - npm run test
  - npm run build

# v2
deploy:
  provider: npm
  edge: true
  email: $NPM_EMAIL
  api_token: $NPM_API_TOKEN
  cleanup: false
  on:
    tags: true
    branch: master
