language: node_js
node_js:
  - '12'
  - '10'
# script:
#   - npm run test
#   - npm run build
# # branches:
# #   only:
# #     - master

# deploy:
#   provider: npm
#   email: $NPM_EMAIL
#   api_key: $NPM_API_TOKEN
#   skip_cleanup: true
#   on:
#     tags: true
#     branch: master

# jobs:
#   include:
#     - stage: build
#       provider: script
#       script:
#         - npm run test
#         - npm run build
#       # branches:
#       #   only:
#       #     - master
#       on:
#         branch: master
#     - stage: publish
#       deploy:
#         provider: npm
#         email: $NPM_EMAIL
#         api_key: $NPM_API_TOKEN
#         skip_cleanup: true
#         on:
#           tags: true
#           branch: master

deploy:
  - provider: script
    script:
      - npm run test
      - npm run build
    on:
      branch: master
  - provider: npm
    email: $NPM_EMAIL
    api_key: $NPM_API_TOKEN
    skip_cleanup: true
    on:
      tags: true